import type { MuscleGroup } from './exercises';

// Maps exercise id → all muscles it works (primary + secondary)
export const MUSCLE_MAP: Record<string, MuscleGroup[]> = {
  bench_press: ["chest", "triceps", "shoulders"],
  incline_bench: ["chest", "triceps", "shoulders"],
  decline_bench: ["chest", "triceps"],
  db_flye: ["chest"],
  cable_crossover: ["chest"],
  push_up: ["chest", "triceps", "shoulders"],
  deadlift: ["back", "hamstrings", "glutes", "forearms"],
  barbell_row: ["back", "biceps", "forearms"],
  pull_up: ["back", "biceps"],
  lat_pulldown: ["back", "biceps"],
  seated_row: ["back", "biceps", "forearms"],
  db_row: ["back", "biceps"],
  ohp: ["shoulders", "triceps"],
  db_shoulder_press: ["shoulders", "triceps"],
  lateral_raise: ["shoulders"],
  front_raise: ["shoulders"],
  face_pull: ["shoulders", "back"],
  barbell_curl: ["biceps", "forearms"],
  db_curl: ["biceps", "forearms"],
  hammer_curl: ["biceps", "forearms"],
  preacher_curl: ["biceps"],
  tricep_pushdown: ["triceps"],
  skull_crusher: ["triceps"],
  overhead_tricep: ["triceps"],
  dip: ["triceps", "chest", "shoulders"],
  squat: ["quads", "glutes", "hamstrings", "core"],
  leg_press: ["quads", "glutes", "hamstrings"],
  leg_extension: ["quads"],
  rdl: ["hamstrings", "glutes", "back"],
  leg_curl: ["hamstrings"],
  hip_thrust: ["glutes", "hamstrings"],
  calf_raise: ["calves"],
  lunges: ["quads", "glutes", "hamstrings"],
  plank: ["core"],
  crunch: ["core"],
  leg_raise: ["core"],
  cable_crunch: ["core"],
};
